services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: match
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - match_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - match_rabbitmq_data:/var/lib/rabbitmq

volumes:
  match_postgres_data:
  match_rabbitmq_data:
